- name: "Provisionning Mongodb (Master)"
  hosts: mongo_master
  become: true
  roles:
    - greendayonfire.mongodb

- name: "Provisionning Mongodb (Slave)"
  hosts: mongo_slave
  become: true
  roles:
   - greendayonfire.mongodb
