# - name: "Provisionning Mongodb (Master)"
#   hosts: mongo_master
#   become: true
#   roles:
#     - greendayonfire.mongodb
#
# - name: "Provisionning Mongodb (Slave)"
#   hosts: mongo_slave
#   become: true
#   roles:
#     - greendayonfire.mongodb

- name: "Provision a Docker Swarm cluster"
  hosts: docker_engine
  become: true
  roles:
    - role: atosatto.docker-swarm
